"""
scanner.py
Scans nearby WiFi networks and presents the results in an organized way.
"""

import csv
import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class NetworkInfo:
    bssid: str
    channel: str
    signal: str
    encryption: str
    essid: str


def scan_networks(monitor_interface: str, scan_time: int = 20) -> list[NetworkInfo]:
    """
    Runs airodump-ng on the monitor-mode interface for `scan_time` seconds,
    saving the output as CSV, and returns the list of networks found.

    Steps:
      1. subprocess.Popen airodump-ng --write scan_temp --output-format csv <interface>
      2. Wait scan_time seconds
      3. Terminate the process
      4. Read and parse the generated CSV (parse_airodump_csv)
    """
    # TODO: implement
    raise NotImplementedError


def parse_airodump_csv(csv_path: str) -> list[NetworkInfo]:
    """
    Parses the CSV file generated by airodump-ng.
    The airodump CSV has two sections (networks and clients) separated by a blank line;
    only the first section (networks/APs) matters here.
    """
    # TODO: use csv.reader, handling airodump-ng's specific format
    raise NotImplementedError


def display_networks(networks: list[NetworkInfo]) -> None:
    """
    Displays the list of networks as a formatted table in the terminal.
    Suggestion: use the `rich` library for a readable table.
    """
    # TODO: implement table using rich.table.Table
    raise NotImplementedError
